In [3]:
import numpy as np
arr = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])

In [4]:
arr

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [5]:
flat = arr.flatten()

In [6]:
flat

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [7]:
flat[0]

np.int64(1)

In [8]:
flat[0:8]

array([1, 2, 3, 4, 5, 6, 7, 8])

In [9]:
sliced = arr[1:4]
sliced[0] = 999
print(arr)  # [10 999 30 40 50]

[[  1   2   3]
 [999 999 999]
 [  7   8   9]
 [ 10  11  12]]


In [10]:
arr = np.array([10, 20, 30, 40, 50])

print(arr[1:4])  # [20 30 40] (slice from index 1 to 3)
print(arr[:3])   # [10 20 30] (first 3 elements)
print(arr[::2])  # [10 30 50] (every 2nd element)

[20 30 40]
[10 20 30]
[10 30 50]


In [11]:
arr = np.array([10, 20, 30, 40, 50])
idx = [0, 2, 4]  # Indices to select
print(arr[idx])  # [10 30 50]

[10 30 50]


In [12]:
arr = np.array([10, 20, 30, 40, 50])
mask = arr > 25  # Condition: values greater than 25
print(arr[mask])  # [30 40 50]

[30 40 50]


# Practice of numpy array, indexing and slicing


In [13]:
import numpy as np

# 1. Create a 3×3 array filled with random numbers and print its shape
arr1 = np.random.rand(3, 3)
print("3x3 Random Array:\n", arr1)
print("Shape:", arr1.shape)

# 2. Convert an array of floats into integers
arr2 = np.array([1.1, 2.2, 3.3], dtype=float)
arr2_int = arr2.astype(int)
print("\nConverted to Integers:", arr2_int)

# 3. Fancy indexing to extract even numbers
arr3 = np.array([1, 2, 3, 4, 5, 6])
even_numbers = arr3[arr3 % 2 == 0]
print("\nEven Numbers:", even_numbers)

# 4. Reshape a 1D array of size 9 into a 3×3 matrix
arr4 = np.arange(1, 10).reshape(3, 3)
print("\n3x3 Reshaped Array:\n", arr4)

# 5. Boolean masking to filter values > 50
arr5 = np.array([10, 60, 45, 100, 30, 75])
filtered = arr5[arr5 > 50]
print("\nNumbers > 50:", filtered)


3x3 Random Array:
 [[0.43100126 0.94669469 0.05998574]
 [0.63071221 0.07439368 0.33592199]
 [0.67804834 0.30400248 0.8247374 ]]
Shape: (3, 3)

Converted to Integers: [1 2 3]

Even Numbers: [2 4 6]

3x3 Reshaped Array:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]

Numbers > 50: [ 60 100  75]
