In [2]:
import numpy as np

In [5]:
arr = np.array([10,54,60,95,22])

In [6]:
np.mean(arr)

np.float64(48.2)

In [7]:
np.std(arr)

np.float64(30.029319006597536)

In [8]:
np.var(arr)

np.float64(901.76)

In [9]:
np.min(arr)

np.int64(10)

In [10]:
np.max(arr)

np.int64(95)

In [11]:
np.sum(arr)

np.int64(241)

In [12]:
np.prod(arr)

np.int64(67716000)

In [13]:
np.median(arr)

np.float64(54.0)

In [14]:
np.percentile(arr, 50)  # For the 50th percentile (median)

np.float64(54.0)

In [15]:
np.argmin(arr)

np.int64(0)

In [16]:
np.argmax(arr)

np.int64(3)

In [18]:
arr1 = np.array([50,30,25,65])
arr2 = np.array([55,35,30,70])
np.corrcoef(arr1, arr2)

array([[1., 1.],
       [1., 1.]])

In [19]:
np.unique(arr)

array([10, 22, 54, 60, 95])

In [20]:
np.diff(arr)

array([ 44,   6,  35, -73])

In [21]:
np.cumsum(arr)

array([ 10,  64, 124, 219, 241])

In [22]:
np.linspace(0, 10, 5)  # 5 numbers from 0 to 10

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [23]:
np.log(arr)

array([2.30258509, 3.98898405, 4.09434456, 4.55387689, 3.09104245])

In [24]:
np.exp(arr)

array([2.20264658e+04, 2.83075330e+23, 1.14200739e+26, 1.81123908e+41,
       3.58491285e+09])