In [1]:
# python zip
l1 = [1, 2, 4]
l2 = [8, 9, 7]
list(zip(l1, l2))

[(1, 8), (2, 9), (4, 7)]

In [2]:
# using python list
import numpy as np
import time

size = 1_000_000_00

l1 = list(range(size))
l2 = list(range(size))

start = time.time()
add = [x + y for x, y in zip (l1, l2)]
end = time.time()
print(add[0:10])

print(end - start)

[0, 2, 4, 6, 8, 10, 12, 14, 16, 18]
11.87572169303894


In [3]:
# using numpy
import numpy as np
import time

size = 1_000_000_00

l1 = np.array(list(range(size)))
l2 = np.array(list(range(size)))

start = time.time()
add = l1 + l2
end = time.time()
print(add[0:10])

print(end - start)

[ 0  2  4  6  8 10 12 14 16 18]
3.734083652496338


In [4]:
# using numpy
import numpy as np
# Creating a 1D NumPy array
arr1 = np.array([1, 2, 3, 4, 5])
print(arr1)
 
# Creating a 2D NumPy array
arr2 = np.array([[1, 2, 3], [4, 5, 6]])
print(arr2)
 
# Checking type and shape
print("Type:", type(arr1))
print("Shape:", arr2.shape)

[1 2 3 4 5]
[[1 2 3]
 [4 5 6]]
Type: <class 'numpy.ndarray'>
Shape: (2, 3)


In [5]:
# Memory Efficiency – NumPy vs. Lists
import sys

list_data = list(range(1000))
numpy_data = np.array(list_data)

print("Python list size:", sys.getsizeof(list_data) * len(list_data), "bytes")
print("NumPy array size:", numpy_data.nbytes, "bytes")

Python list size: 8056000 bytes
NumPy array size: 8000 bytes


In [ ]:
import numpy as np
import timeit

size = 1_000_000
py_list = list(range(size))
np_arr = np.arange(size)

print(timeit.timeit('[x*2 for x in py_list]', globals=globals(), number=5))
print(timeit.timeit('np_arr*2', globals=globals(), number=5))


# Practice In numpy

In [ ]:
# Create a NumPy array from 10 to 100 + print shape
import numpy as np
arr = np.arange(10,101)
print(arr)
print(arr.shape)

In [ ]:
# Compare time: Python list multiplication vs NumPy array multiplication
import numpy as np
import timeit

size = 1_000_000

py_list = list(range(size))
np_arr = np.arange(size)

t_list = timeit.timeit('[x*2 for x in py_list]', globals=globals(), number=10)
t_np = timeit.timeit('np_arr*2', globals=globals(), number=10)

print("Python list time:", t_list)
print("NumPy array time:", t_np)

In [ ]:
# Memory size of a NumPy array with 1 million elements
import numpy as np

arr = np.ones(1_000_000, dtype=np.float64)
print(arr.nbytes, "bytes")
